config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/about', to: 'pages#about'

  resources :articles
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 3, maximum: 50}
    validates :description, presence: true, length: { minimum: 10, maximum: 300}, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end
    
    def new
        @article = Article.new
    end

    def create
        #render plain: params[:article].inspect
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
        @article = Article.find(params[:id])
    end

    private
        def article_params
            params.require(:article).permit(:title, :description)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end

    def about

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Showing all articles</h1>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
        <tr>
            <td scope="row"><%= article.id %></td>
            <td><%= article.title %></td>
            <td><%= article.description %></td>
            <td><%= link_to "Show", article_path(article) %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create an Article</h1>


<% if @article.errors.any? %>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @article do |f|%>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>   
    </p>
    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description%>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page of my blog app.</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>This is the home page of my blog app.</h1>

<%= link_to 'About Us', pages_about_path %>